---
execute: 
  echo: false
---

# PLSR Validation

There are two types of validation: *internal* (within-cohort), and *external* (cross-cohort) validations. For the internal validation, a leave-one-out cross validation was used to build the final PLSR model across the whole cohort population. For the external validation, the PLSR model was built using all training case samples. For both internal and external validations, we used the optimal number of PLSR component computed during the training.

::: callout-note
## Implementation note

Codes are writtin in R language. PLSR training is provided by the [`caret`](https://topepo.github.io/caret/) package and the ROC analysis by [`pROC`](https://xrobin.github.io/pROC/) package. We also use [`tidyverse`](https://www.tidyverse.org/) set of packages for data frame manipulations.
:::


## MESA validation results

  a.  [Hypertension](pages/Val_MESA_Hypertension.html)
  b.  [Diabetes](pages/Val_MESA_Diabetes.html)
  c.  [Obesity](pages/Val_MESA_Obesity.html)
  d.  [Hypercholesterolemia](pages/Val_MESA_Hypercholesterolemia.html)
  e.  [Smoking](pages/Val_MESA_Smoking.html)


## UKBB validation results

  a.  [Hypertension](pages/Val_UKBB_Hypertension.html)
  b.  [Diabetes](pages/Val_UKBB_Diabetes.html)
  c.  [Obesity](pages/Val_UKBB_Obesity.html)
  d.  [Hypercholsterolemia](pages/Val_UKBB_Hypercholesterolemia.html)
  e.  [Smoking](pages/Val_UKBB_Smoking.html)
